### ISSUE TITLE
Dashboard won't start when /onyx doesn't exist in ZooKeeper

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx-dashboard#9]
This bug report is totally lame, but just a heads up that Component throws an odd exception when ZK doesn't have an `/onyx` directory.

**Comment by lbradstreet** [comment]
Totally had some code for that already (rebooted my VMs and it started new ZK containers with new data, wheeeee).

Suboptimally fixed in: https://github.com/lbradstreet/onyx-dashboard/commit/169949f300b82802bb6c691de5aa82de859b2813

Ultimately I'd like the whole system to still startup and just notify the front end that it couldn't retrieve the deployments but this will do for now.

**Comment by lbradstreet** [comment]
Will leave this open for better solution. Will try for 0.1.

**Comment by MichaelDrogalis** [comment]
Concur.

**Comment by lbradstreet** [comment]
Seems to handle a missing zookeeper cluster now by connection retry
